### PR TITLE
Initial attempt at a release checklist template

### LINKED ISSUE #178: Sample Release Checklist to improve Release Automation
Creating this Work in Progress checklist based on the [release doc](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) to capture what main activities happen during a release, and to annotate which activities can and should be automated in some fashion.  This should serve to streamline release activities and help release champions complete all the required tasks.

One Week Prior to Release:
- [ ] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [ ] **Run a trial release pipeline** to ensure less surprises on release day

Release Week Checklist:
- [ ] **Add website banner** (_automate_* via github workflow - champion creates a website issue (likely based on a template), on creation of a website issue with particular subject and contents (enforced by a template), a workflow is triggered which creates a PR for the website, similar to this [example PR](https://github.com/AdoptOpenJDK/openjdk-website/pull/702/files))
- [ ] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Typically been separating hotspot and openj9 pipelines in release week.  Capture pertinent info in a table per implementation.
- [ ] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptopenjdk.net/) to view a summary of test results.  Create a summary of test failures per pipeline to add to the [Promote release issue](https://github.com/AdoptOpenJDK/TSC/issues/new?assignees=&labels=&template=promote-release.md&title=Promote+AdoptOpenJDK+Version+%3Cx%3E) in the TSC repo which can be revamped to include a (shorter version of this checklist and ideally contains a succinct table as per example below, you can use [trss-parser](https://www.npmjs.com/package/trss-parser).  (_automate_* via github workflow or Jenkins job trigger to add a comment/table to TSC release issue)
- [ ] **Triage** each build and test failure (using [Triage guidelines](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  
- [ ] **Fix** blocking failures if they exist.
- [ ] **Get TSC 'ready to publish' approval**, once no blocking failures exist.
- [ ] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [ ] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
- [ ] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/AdoptOpenJDK/openjdk-website/blob/master/src/handlebars/support.handlebars))
- [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptopenjdk.net/release_notes.html))
- [ ] **Run homebrew-cask_updater** (via [Jenkins homebrew-cask_updater job link](https://ci.adoptopenjdk.net/job/homebrew-cask_updater/)) once binaries published successfully (this can be automated / triggered by a test for published artifacts)
- [ ] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)

Hotspot
|Job name / ID |scmReference/tag|Other Args if not defaults| Summarized Results | Published |
| --- | --- | --- | --- | --- | 
| [jdk8 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline) |  |  | |  |
| [jdk11 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline) |  |  | | |
| [jdk15 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline) |  |  | | |
|  |  |  | | |

OpenJ9
|Job name / ID |scmReference/tag|Other Args if not defaults| Summarized Results |Published |
| --- | --- | --- | --- | --- |
| [jdk8 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline) |  |  | |  |
| [jdk11 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline) |  |  | |  |
| [jdk15 Pipeline ID](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline) |  |  | |  |
|  |  |  | |  |

### LINKED ISSUE #215: Proposal: To Create a Tick-List Issue Template for Releases
**The Problem**

When a release happens, people don't know what parts of a release have been handled, or by whom, unless they ask around.

**The Cause**

The release document is a read-only document, and does not allow a person to track their progress for a specific release.

**The Proposed Solution**

To create checklist/s that can be duplicated and ticked off on a per-release basis.

One option is to move the release steps in [RELEASING.md](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) into issue template files in the same repo, and to put links in RELEASING.md that connect to them. 

The logic behind this is to retain information centralization in RELEASING.md, while preventing double-commits (were we to copy the release steps rather than move them).

The debate is open.

### PR DESCRIPTION
**Pull request by smlambert**
Fixes #178
Fixes #215 
Signed-off-by: Shelley Lambert <slambert@gmail.com>

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
To comments:

> **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)

Now that we're doing the weekly runs in theory this should be done regular enough that it might not be strictly necessary, so I'm split on whether this is required (Obviously nice, but takes time, and how many checks would you do on the output compared to the weekly runs?)

We should also clarify when the "Launch build pipelines" box (and some of the follow-on ones on the list) should be checked. We have some pipelines that are initiated separately (e.g. EA for OpenJ9/aarch64, or ARM32 JDK8u HotSpot) so need to be clear on what the check means - perhaps the release champion should be require to duplicate the lines in the checklist as appropriate for any pipelines initated separately? Another option would be to create multiple copies of the template for each pipeline required, which would likely be the most descriptive/clear option.

**Comment by smlambert** [comment]
Yes this is still a draft... I just pushed it so that I could point to the paragraph describing the release champion's role.

I like to have most information summarized in one place, and personally imagine that each pipeline that would be launched would be listed in this issue (including if we break a version up by primary/secondary platforms, or ga/ea or in whatever way they are divided).

For notes to each checkbox, they can link to separate issues (like 1 or more triage issues) if need be.  In order for people to get a better sense of this, I likely should create an actual issue from the template once its a bit more refined (based on a previous or pretend release) to see how it might look.

**Comment by smlambert** [comment]
When the issue is created, we can also assign up to 10 assignees (who could all then edit and check off things), so while there is a release champion, there is really a release team all helping who can/should be assigned so they can edit and update the issue.

**Comment by sxa** [comment]
(Need to validate that assignees can definitely edit)

**Comment by lumpfish** [comment]
The reality is that this section:
```
 [ ] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.
  - jdk8 pipeline(s): 
  - jdk11 pipeline(s): 
  - jdkxx pipeline(s): 
```
is likely too optimistic.

Builds / test jobs are likely to fail, and will need resubmitting.  In some cases resubmitting the whole pipeline for the affected platform(s) is the most sensible thing to do - in other cases it would be rerunning individual test jobs.

Without going too much into the detail of how to do that (though I think instructions / guidance would likely be needed for anyone new-ish to the role) I think at least mentioning that reruns are possible / likely would be 'honest'.

**Review by andrew-m-leonard — APPROVED** [review]
Looks good at an initial attempt, let's give it a go...

**Review by sxa — APPROVED** [review]

**Comment by sxa** [comment]
Merging on the basis that we can adjust it later and everyone on the release call is ok with it

**Pull request merged**
